Challenge/implement challenges 16
CarterLankford/MentorExercises pull request #22
Opened 2019-06-17 19:10 UTC by CarterLankford

Adding in directory for challenges that come up but would be out of place in the other directories.

2019-06-18 20:40 UTC, vinceynhz requested changes
Before each call to `System.out,println`, add a comment line to explain what is the expected output, and in the weird cases, include a note on why. For example:
```java
myArray = "/".split("/");
// This should print an empty array: [] 
// Because the only delimiter adds a single empty string at the end of the array, which are ignored by the split method
System.out.println(Arrays.toString(myArray));
```

2019-06-19 15:03 UTC, CarterLankford commented
I've added in the requested information.

2019-06-20 17:11 UTC, vinceynhz commented on Challenges/MyStringSplit.java
> +        //Actual Result: [, resource, , path, , test]
Actual result is: [, , resource, , path, , test] There are some back to back delimiters which create empty strings in between

2019-06-20 17:11 UTC, vinceynhz approved these changes

2019-06-20 17:11 UTC, merged