Adding in exercise to demonstrate inheritance
CarterLankford/MentorExercises pull request #23
Opened 2019-06-18 17:26 UTC by CarterLankford

V1 and V2 were added to show the before and after, so that I might use it as a reference. V2 is when the interface is added in.

2019-06-18 21:09 UTC, vinceynhz commented
I want to see the responses to the questions in #21 before reviewing the code. Part of the exercise is to be able to think on inheritance before writing code :)

2019-06-18 21:09 UTC, vinceynhz requested changes
I want to see the responses to the questions in #21 before reviewing the code. Part of the exercise is to be able to think on inheritance before writing code :)

2019-06-19 15:45 UTC, CarterLankford commented
Have added the requested changes.

2019-07-16 16:32 UTC, vinceynhz approved these changes

2019-07-16 16:32 UTC, merged